/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Text = string;
export type FontSize = string;
export type FontWeight = number;
export type Text1 = string;
export type FontSize1 = string;
export type FontWeight1 = number;
export type LinkToTheImage = string;

export interface ConfigureTheImage {
  title?: TitleSettings;
  subTitle?: SubtitleSettings;
  imageLink?: LinkToTheImage;
  [k: string]: unknown;
}
export interface TitleSettings {
  text?: Text;
  fontSize?: FontSize;
  fontWeight?: FontWeight;
  color?: FontColor;
  backgroundColor?: BackgroundColor;
  [k: string]: unknown;
}
export interface FontColor {
  [k: string]: unknown;
}
export interface BackgroundColor {
  [k: string]: unknown;
}
export interface SubtitleSettings {
  text?: Text1;
  fontSize?: FontSize1;
  fontWeight?: FontWeight1;
  color?: FontColor1;
  [k: string]: unknown;
}
export interface FontColor1 {
  [k: string]: unknown;
}
